urls.py
from django.conf.urls import patterns, include, url
from django.views.static import serve
from django.views.generic import RedirectView
import os
import settings
import app.views as app_views
import app.urls as app_urls
import teacher.views as teacher_views
import school.urls as school_urls
import api.urls as api_urls
import teacher.urls as teacher_urls
import views
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.index, name="index"),
    # the built-in sign-in/out module
    url(r'^login/$', app_views.login , name="login"),
    url(r'^login/(?P<redirect_after>[/%a-zA-Z0-9_\-]+)/$',
        app_views.login, name="login_redirect"),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
            {'template_name': os.path.join(settings.TEMPLATE_DIRS[0],
                'app/logout.html'), 'next_page': '/'}, name="logout"),
    url(r'^register/$', app_views.register, name='register'),
    url(r'^teacher/register/$', teacher_views.RegisterView.as_view(),
        name='teacher_register'),
    url(r'^manageRegister/$', app_views.manage_register,
        name='manage_register'),
    url(r'^manageRegister/(?P<sort_by_date>\w+)/$', app_views.manage_register,
        name="manage_register"),
    url(r'^manageRegister/(?P<sort_by_date>\w+)/(?P<sort_by_status>\w+)/$',
        app_views.manage_register, name="manage_register"),
    url(r'^manageSchool/$', app_views.manage_school,
        name='manage_school'),
    url(r'^manageSchool/(?P<sort_by_balance>\w+)/$', app_views.manage_school,
        name="manage_school"),
    url(r'^manageSchool/(?P<sort_by_balance>\w+)/(?P<sort_by_status>\w+)/$',
        app_views.manage_school, name="manage_school"),


    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^sms-manager/$', app_views.admin_sms_manager,
        name='admin_sms_manager'),
    #object comments
    #url(r'^comments/', include(comment_urls)),
    
    # urls for app app
    url(r'^app/', include(app_urls)),
    # url for school app
    #url(r'^school/(?P<school_id>\d+)/', include(school_urls)),
    url(r'^school/', include(school_urls)),
    url(r'^teacher/(?P<teacher_id>\d*)/', include(teacher_urls)),
    url(r'^api/', include(api_urls)),

    url(r'^about/$', views.about, name="about"),
    url(r'^videos/$', views.videos, name="videos"),
    url(r'help/(?P<page>[\w\-]*)$', views.help, name="help"),

#    url(r'^profile/', 'views.get_absolute_url'),

    #url for help app

    (r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    (r'^(?P<path>robots.txt)$', serve, {'document_root': settings.STATIC_ROOT}),
    url(r'^user_uploaded/(?P<path>.*)$', serve,
            {'document_root': settings.TEMP_FILE_LOCATION},
            name='user_upload'),
    (r'^favicon\.ico$', RedirectView.as_view(url = '/static/images/favicon.ico')),
)

app/models.py
#coding: utf-8
from ConfigParser import SafeConfigParser
import os
import codecs
from datetime import date
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import F
from django.db import transaction
from recaptcha.client import captcha
from django.db import models
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from sms.utils import send_email
import settings


SCHOOL_SETTING_FOLDER = settings.SCHOOL_SETTING_FOLDER

ORGANIZATION_LEVEL_CHOICES = (
        ('T', u'Trường'),
        ('P', u'Phòng'),
        ('S', u'Sở'))
ORGANIZATION_STATUS_CHOICES = (
        (1, u'Đã kích hoạt'),
        (2, u'Đã khóa'))
POSITION_CHOICE = (
        ('HOC_SINH', u'Học sinh'),
        ('GIAO_VU', u'Giáo vụ'),
        ('GIAO_VIEN', u'Giáo viên'),
        ('HIEU_PHO', u'Hiệu phó'),
        ('HIEU_TRUONG', u'Hiệu trưởng'),
        ('GIAM_DOC_SO', u'Giám đốc sở'),
        ('TRUONG_PHONG', u'Trưởng phòng'))

KHOI_CHOICES = (
        ('2', u'Cấp 2'),
        ('3', u'Cấp 3'))

SCHOOL_ACTION_STATUS = (
        (0, u'Trường mới'),
        (1, u'Đang học kỳ 1'),
        (2, u'Đang học kỳ 2'),
        (3, u'Đang nghỉ hè'))
SCHOOL_TYPES = (('0', u'Công lập'), ('1', u'Giáo dục thường xuyên'))

TINH_CHOICES = (('1',u'An Giang'), ('2',u'Bà Rịa-Vũng Tàu'), ('3',u'Bạc Liêu'),
        ('4',u'Bắc Cạn'), ('5',u'Bắc Giang'), ('6',u'Bắc Ninh'), ('7',u'Bến Tre'),
        ('8',u'Bình Dương'), ('9',u'Bình Định'), ('10',u'Bình Phước'),
        ('11',u'Bình Thuận'), ('12',u'Cà Mau'), ('13',u'Cao Bằng'), ('14',u'Cần Thơ'),
        ('15',u'Đà Nẵng'), ('16',u'Đắk Lắk'), ('17',u'Đắk Nông'), ('18',u'Điện Biên'),
        ('19',u'Đồng Nai'), ('20',u'Đồng Tháp'), ('21',u'Gia Lai'), ('22',u'Hà Giang'),
        ('23',u'Hà Nam'), ('24',u'Hà Nội'), ('25',u'Hà Tĩnh'), ('26',u'Hải Dương'),
        ('27',u'Hải Phòng'), ('28',u'Hòa Bình'), ('29',u'Hồ Chí Minh'),
        ('30',u'Hậu Giang'), ('31',u'Hưng Yên'), ('32',u'Khánh Hòa'),
        ('33',u'Kiên Giang'), ('34',u'Kom Tum'), ('35',u'Lai Châu'), ('36',u'Lào Cai'),
        ('37',u'Lạng Sơn'), ('38',u'Lâm Đồng'), ('39',u'Long An'), ('40',u'Nam Định'),
        ('41',u'Nghệ An'), ('42',u'Ninh Bình'), ('43',u'Ninh Thuận'), ('44',u'Phú Thọ'),
        ('45',u'Phú Yên'), ('46',u'Quảng Bình'), ('47',u'Quảng Nam'),
        ('48',u'Quảng Ngãi'), ('49',u'Quảng Ninh'), ('50',u'Quảng Trị'),
        ('51',u'Sóc Trăng'), ('52',u'Sơn La'), ('53',u'Tây Ninh'), ('54',u'Thái Bình'),
        ('55',u'Thái Nguyên'), ('56',u'Thanh Hóa'), ('57',u'Thừa Thiên-Huế'),
        ('58',u'Tiền Giang'), ('59',u'Trà Vinh'), ('60',u'Tuyên Quang'),
        ('61',u'Vĩnh Long'), ('62',u'Vĩnh Phúc'), ('63',u'Yên Bái'))

REGISTER_STATUS_CHOICES = (('DA_CAP', u"Đã cấp"), ('CHUA_CAP', u"Chưa cấp"))

SUBJECT_CHOICES = ((1,u'Toán'), (2, u'Vật lí'), (3, u'Hóa học'), (4, u'Sinh học'),
        (5, u'Ngữ văn'), (6, u'Lịch sử'), (7, u'Địa lí'), (8, u'Ngoại ngữ'),
        (9, u'GDCD'), (10, u'Công nghệ'), (11, u'Thể dục'), (12, u'Âm nhạc'),
        (13, u'Mĩ thuật'), (14, u'NN2'), (15, u'Tin học'), (16, u'GDQP-AN'))

GRADES_CHOICES = ((6, u'Lớp 6'), (7, u'Lớp 7'), (8, u'Lớp 8'), (9, u'Lớp 9'),
        (10, u'Lớp 10'), (11, u'Lớp 11'), (12, u'Lớp 12'))

TERMS=((1, u'Kì 1'), (2, u'Kì 2'))

LOGIN_TYPE = ['DEMO_LOGIN_SCHOOL', 'DEMO_LOGIN_TEACHER', 'DEMO_LOGIN_UPPER',
'DEMO_LOGIN_STUDENT']

class MyConfigParser(SafeConfigParser):
    def write(self, fp):
        for section in self._sections:
            fp.write("[%s]\n" % section)
            for (key, value) in self._sections[section].items():
                if key == "__name__":
                    continue
                if (value is not None) or (self._optcre == self.OPTCRE):
                    key = " = ".join((key, unicode(value).replace('\n', '\n\t')))
                fp.write("%s\n" % key)
            fp.write("\n")

class Organization(models.Model):
    SEMESTER_STATUS = [u'Chưa thiết lập', u'Học kỳ I',
                       u'Học kỳ II', u'Học kỳ hè']
    name = models.CharField(u'Tên tổ chức', max_length=100)
    level = models.CharField(u"cấp", max_length=2,
            choices=ORGANIZATION_LEVEL_CHOICES)
    organization_status = models.SmallIntegerField(max_length=3, default=1,
            choices=ORGANIZATION_STATUS_CHOICES)
    #------- those attributes is used for School only -------------------------
    school_level = models.CharField(u"Khối học", max_length=6, blank=True,
            null=True, choices=KHOI_CHOICES)
    status = models.SmallIntegerField(max_length=3, blank=True, null=True,
            choices=SCHOOL_ACTION_STATUS)
    school_type = models.CharField(u'Loại trường', max_length=30, blank=True,
            choices=SCHOOL_TYPES)
    balance = models.FloatField(u'Tài khoản', default=50)
    #--------------------------------------------------------------------------
    upper_organization = models.ForeignKey('self', blank=True, null=True,
            verbose_name='Trực thuộc')
    manager_name = models.CharField("Tên thủ trưởng", max_length=100, null=True)
    address = models.CharField("Địa chỉ", max_length=255, blank=True, null=True)
    phone = models.CharField("Điện thoại", max_length=20, blank=True, null=True)
    email = models.EmailField(max_length=50, blank=True, null=True)
    district = models.CharField(u'Huyện',max_length = 100,blank=True,null=True,
            default='')
    allow_recover_password = models.BooleanField(default=False,blank=True)

    class Meta:
        verbose_name_plural = "Tổ chức"

    def get_current_year(self):
        return self.year_set.latest('time')

    def get_status(self):
        if self.level == 'T':
            try:
                year = self.year_set.latest('time')
                return Organization.SEMESTER_STATUS[self.status]\
                       + u' năm ' + year.__unicode__()
            except Exception:
                return Organization.SEMESTER_STATUS[0]
        else:
            return ''

    def _atomic_increase_bl(self):
        Organization.objects.select_for_update().filter(id=self.id)\
                .update(balance=F('balance') + 1)

    @transaction.commit_on_success
    def _atomic_decrease_bl(self):
        temp = Organization.objects.select_for_update().get(id=self.id)
        if temp.balance > 0:
            temp.balance -= 1
            temp.save()
            return True
        else: return False

    #TODO: check quota for school
    def is_allowed_sms(self):
        bl = self._atomic_decrease_bl()
        return bl
        #if self.id in settings.SCHOOL_ALLOWED_SMS:
        #    return True
        #else:
        #    return False

    def get_active_students(self):
        return self.pupil_set.filter(unc_class_id=None,
                disable=False).distinct()
    
    def get_teachers(self):
        return self.teacher_set.all()

    def get_students(self):
        return self.pupil_set.all()

    def save_settings(self, attribute, value):
        if type(attribute) != str or (type(value) != str
            and type(value) != unicode and type(value) != int):
            raise Exception('InvalidArgumentType')
        try:
            setting_file_name = str(self.id)
            setting_file_name = os.path.join(SCHOOL_SETTING_FOLDER,
                                             setting_file_name)
        except Exception as e:
            print e
            raise Exception('OrganizationNotSaved')

        setting = MyConfigParser()
        try:
            file = codecs.open(setting_file_name, 'r', 'utf-8')
        except IOError:
            file = codecs.open(setting_file_name, 'wb', 'utf-8')
            file.close()
            file = codecs.open(setting_file_name, 'r', 'utf-8')
        setting.readfp(file)
        file.close()
        if not setting.has_section('school'):
            setting.add_section('school')
        setting.set('school', attribute, unicode(value))
        file = codecs.open(setting_file_name, 'wb', 'utf-8')
        setting.write(file)
        file.close()

    def get_setting(self, attribute):
        if type(attribute) != str:
            raise Exception('InvalidArgumentType')

        if self.id:
            setting_file_name = str(self.id)
            setting_file_name = os.path.join(SCHOOL_SETTING_FOLDER,
                    setting_file_name)
        else:
            raise Exception('OrganizationNotSaved')

        setting = MyConfigParser()
        try:
            file = codecs.open(setting_file_name, 'r', 'utf-8')
            setting.readfp(file)
            result = setting.get('school', attribute)
        except  Exception as e:
            print e
            if attribute == 'lock_time':
                self.save_settings(attribute, 24)
                return 24
            else:
                self.save_settings(attribute, '')
                return ''
        try:
            if len(result) > 1 and result[0] == '[' and result[-1] == ']':
                return eval(result)
            else:
                if attribute == 'lock_time' and not result:
                    self.save_settings('lock_time', 24)
                    result = 24
                return result
        except Exception as e:
            print e
            return ''

    def __unicode__(self):
        return self.name

class OrganizationForm(forms.Form):
    name = forms.CharField(max_length=100) #tên đơn vị. tổ chức
    level = forms.CharField(max_length=2,
                            widget=forms.RadioSelect(
                            choices=ORGANIZATION_LEVEL_CHOICES)) #Cấp
    upper_organization = forms.ModelChoiceField(queryset=Organization.objects.all())
    address = forms.CharField(max_length=255) #
    phone = forms.CharField(max_length=20)
    email = forms.EmailField(max_length=50)

#class TruongnhaUser(User):
#    organization = models.ForeignKey(Organization, verbose_name='Đơn vị')
#    position = models.CharField(choices=POSITION_CHOICE, null=True, blank=True, max_length=15)

templates/app/admin_sms_manager.html
{% extends "base.html" %}

{% block breadcrumb %}
    {{ block.super }}
    {% load breadcrumb_tags %}
    {% add_crumb 'Lịch sử nhắn tin hệ thống' %}
{% endblock %}

{% block content %}
    <div id="submenu" class="btn-toolbar">
      <div class="btn-group">
          <form class="form-inline" action="{% url 'count_sms' %}" name="info"
                method="post" style="margin-bottom:0;"> {% csrf_token %}
                  <div class="input-prepend" style="margin-right: 5px;">
                      <span class="add-on">Từ ngày</span>
                      <input id="id_date1" name="firstDate"
                          class="datepicker input-small"
                          type="text"
                          style="margin-top: 0;"
                          value="{{day}}/{{month}}/{{year}}">
                  </div>

                  <div class="btn-group" data-toggle="buttons-radio">
                          <button type="submit" class="btn active"
                              name="type1" value="1">
                              Tất cả
                          </button>
                          <button type="submit" class="btn"
                              name="type1" value="2">
                              Đã gửi
                          </button>
                          <button type="submit" class="btn"
                              name="type1" value="3">
                              Thất bại
                          </button>
                  </div>
          </form>
      </div>
    </div>

    <table id="sms-table" class="table" width="100%">
        <tr>
            <th>
                STT
            </th>
            <th>
                Người nhận
            </th>
            <th>
                SĐT
            </th>
            <th>
                Ngày gửi
            </th>
            <th>
                Nội dung
            </th>
            <th>
                Trạng thái
            </th>
        </tr>
        {% for sms in smses %}
            {% if sms.success %}
            <tr class="{{ sms.id }} sms" data-status="success">
            {% else %}
            <tr class="{{ sms.id }} sms failed" data-status="failed">
            {% endif %}
                <td>
                    {{ forloop.counter }}
                </td>
                <td>
                  {{ sms.receiver }}
                </td>
                <td>
                    {{ sms.phone }}
                </td>
                <td>
                    {{ sms.modified|date:"SHORT_DATETIME_FORMAT" }}
                </td>
                <td class="truncated" style="max-width:350px;"
                    title="{{ sms.content }}">
                    {{ sms.content }}
                </td>
                <td>
                    {% if sms.recent %}
                        Đang gửi
                    {% else %}
                        {% if sms.success %}
                            Thành công
                        {% else %}
                        <a class="click-tooltip"
                            href="#"
                            title="{{l.failed_reason}}-{{l.get_failed_reason}}">
                            Thất bại</a>
                        {% endif %}
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/app/create_profile.html
{% extends "base.html" %}
 	
	{% block content %}
 	
 	<h1>Tạo thông tin cá nhân cho tài khoản: {{ user }} </h1>
 	
 	<div id="create_profile">
 	<form method="POST" action="" enctype="multipart/form-data">
 	<dl>
 	{% for field in form %}
 	<dt>{{ field.label_tag }}</dt>
 	<dd>{{ field }}</dd>
 	{% if field.help_text %}<dd>{{ field.help_text }}</dd>{% endif %}
 	{% if field.errors %}<dd class="form_errors">{{ field.errors }}</dd>{% endif %}
 	{% endfor %}
 	</dl>
 	<input type="submit" name="submit" value="Update" id="submit">
 	</form>
 	</div>
 	
 	{% endblock content %}

templates/app/logout.html
<meta HTTP-EQUIV="REFRESH" content="0; url=/login">

templates/app/manage_register.html
{% extends "base.html" %}

{% block breadcrumb %}
    {{ block.super }}
    {% load breadcrumb_tags %}
    {% add_crumb 'Các đăng ký sử dụng' %}
{% endblock %}

{% block js %}
    <script type="text/javascript" src="/static/js/template_js/manage_register.js?{{ VERSION }}"></script>
{% endblock %}

{% block content %}
    {#    <h2>Danh sách đăng ký tài khoản khách hàng</h2>#}
    {% if registers %}
        <div id="submenu" class="btn-toolbar">
            <button id="showRegistered" class="btn"
                    title="Ẩn/Hiện những đăng ký đã cấp">Ẩn đăng ký đã cấp
            </button>

            <button id="createSelected" class="btn btn-primary"
                    title="Tạo tài khoản cho những đăng ký đã chọn">Tạo tài khoản
            </button>

            <button id="delSelected" class="btn btn-danger"
                    title="Xóa những đăng ký đã chọn và gửi thông báo với những đăng ký chưa cấp">Xóa
            </button>

            <div class="pull-right">
                <div class="btn-group">
                        <button id="textSms" class="btn btn-warning"
                                title="Gửi thông báo đến những đăng kí đã chọn">
                            <i class="icon-envelope"></i>
                            Gửi thông báo
                        </button>
                </div>
            </div>
        </div>
        <table class="table" id="registerTable">
            <thead>
            <tr>
                <th title="Chọn tất cả" style="text-align: center;">
                    <input type="checkbox" id="checkbox_all" class="registerCheckbox"/>
                </th>
                <th style="text-align: center">STT</th>
                <th style="text-align: center">
                    <a href="{% url 'manage_register' short_by_date short_by_status %}">
                        Trạng thái
                    </a>
                </th>
                <th>Người đăng ký</th>
                <th>Số điện thoại</th>
                <th>Email</th>
                <th>Tên trường</th>
                <th style="text-align: center">Cấp</th>
                <th>Địa chỉ</th>
                <th>Tỉnh/Thành phố</th>
                <th>
                    <a href="{% url 'manage_register' short_by_date short_by_status %}">
                        Ngày đăng ký
                    </a>
                </th>
                <th style="text-align: center" class="accountInfo">Tài khoản</th>
                <th style="text-align: center" class="accountInfo">Mật khẩu</th>

            </tr>
            </thead>
            <tbody>
            {% for register in registers %}
                <tr class="{{ register.id }} register">
                    <td style="text-align: center; padding-left: 4px;">
                        <input type="checkbox" id="checkbox_{{register.id}}" class="registerCheckbox"/>
                    </td>
                    <td style="text-align: center">{{ forloop.counter }}</td>
                    <td style="text-align: center;" class="status">{{ register.get_status_display }}</td>
                    <td style="padding-left: 8px;">{{ register.register_name }}</td>
                    <td style="padding-left: 8px;">{{ register.register_phone }}</td>
                    <td style="padding-left: 8px;">{{ register.register_email }}</td>
                    <td style="padding-left: 8px;">{{ register.school_name }}</td>
                    <td style="text-align: center;">{{ register.get_school_level_display }}</td>
                    <td style="padding-left: 8px;">{{ register.school_address }}</td>
                    <td style="padding-left: 8px;">{{ register.get_school_province_display }}</td>
                    <td style="padding-left: 8px;">{{ register.register_date|date:"SHORT_DATE_FORMAT" }}</td>
                </tr>

            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Không có đăng ký nào</p>
    {% endif %}
    <div id="smsWindow" class="popup-windows">
        <section>
            <table class="table table-condensed no-border">
                <tr>
                    <th class="from tr">Người gửi</th>
                    <td>
                        {{ user.last_name }} {{ user.first_name }} ({{ user }})
                    </td>
                </tr>
                <tr>
                    <th class="to tr">Người nhận</th>
                    <td>
                        <button id="showChosenRegister">Chưa chọn đăng ký nào</button>
                    </td>
                </tr>

                <tr>
                    <th>Nội dung</th>
                    <td>
                        <textarea class="smsContext item popupTextarea"
                                  id="smsContent"
                                  rows="4"
                                  style="width: 250px; max-width: 250px; height: 100px;"></textarea>
                    </td>
                </tr>

                <tr>
                    <th></th>
                    <td>
                        <button id="send" class="btn btn-danger"
                                data-loading-text="Đang gửi..."
                                disabled="disabled">
                            <i class="icon-envelope"></i>
                            Gửi thông báo
                        </button>
                        <button id="smsClose" class="btn">Thôi</button>
                    </td>
                </tr>

                <tr>
                    <th></th>
                    <td>
                        <div class="progress progress-striped active"
                             id="smsProgressbar" style="display: none;">
                            <div class="bar"
                                 style="width: 90%;"></div>
                        </div>
                        <div class="alert alert-error" id="smsErrorDetail"
                             style="display: none;">
                        </div>
                    </td>
                </tr>
            </table>
        </section>
    </div>
{% endblock %}

templates/app/manage_school.html
{% extends "base.html" %}

{% block breadcrumb %}
    {{ block.super }}
    {% load breadcrumb_tags %}
    {% add_crumb 'Các trường trong hệ thống' %}
{% endblock %}

{% block js %}
    <script type="text/javascript" src="/static/js/template_js/manage_school.js?{{ VERSION }}"></script>
{% endblock %}

{% block content %}
    {% if schools %}
        <div id="submenu" class="btn-toolbar">
            <button id="showActivated" class="btn"
                    title="Ẩn/Hiện những trường đã bị vô hiệu">Ẩn các trường đã khóa
            </button>

            <button id="ActivateSelected" class="btn btn-primary"
                    title="Kích hoạt các trường đang bị hô hiệu">Kích hoạt
            </button>

            <button id="DeactivateSelected" class="btn btn-primary"
                    title="Khóa các trường đã chọn">Khóa
            </button>

{#            <button id="delSelected" class="btn btn-danger"#}
{#                    title="Xóa chọn">Xóa#}
{#            </button>#}
        </div>
        <table class="table" id="schoolTable">
            <thead>
            <tr>
                <th title="Chọn tất cả" style="text-align: center;">
                    <input type="checkbox" id="checkbox_all" class="schoolCheckbox"/>
                </th>
                <th style="text-align: center">STT</th>
                <th style="text-align: center">
                        Tên trường
                </th>
                <th >Trạng thái</th>

                <th>
                    <a href="{% url 'manage_school' sort_by_balance sort_by_status %}">
                    Kì học
                    </a>
                </th>
                <th style="text-align: center">Cấp</th>
                <th style="text-align: center">Hiệu trưởng</th>
                <th>Số điện thoại</th>
                <th>Email</th>
                <th>Địa chỉ</th>

                <th>
                    <a href="{% url 'manage_school' sort_by_balance sort_by_status %}">
                        Tài khoản
                    </a>
                </th>
            </tr>
            </thead>
            <tbody>
            {% for school in schools %}
                <tr class="{{ school.id }} school">
                    <td style="text-align: center; padding-left: 4px;">
                        <input type="checkbox" id="checkbox_{{school.id}}" class="schoolCheckbox"/>
                    </td>
                    <td style="text-align: center">{{ forloop.counter }}</td>
                    <td style="padding-left: 8px;">{{ school.name }}</td>
                    <td style="text-align: center;" class="status">{{ school.get_organization_status_display }}</td>
                    <td style="text-align: center;">{{ school.get_status_display }}</td>
                    <td style="text-align: center;">{{ school.get_school_level_display }}</td>
                    <td style="padding-left: 8px;">{{ school.manager_name }}</td>
                    <td style="padding-left: 8px;">{{ school.email }}</td>
                    <td style="padding-left: 8px;">{{ school.phone }}</td>
                    <td style="padding-left: 8px;">{{ school.address }}</td>
                    <td style="padding-left: 8px;">{{ school.balance }}</td>
                </tr>

            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Không có trường nào</p>
    {% endif %}

{% endblock %}